/*
 * KVM VIRT experiment: EPT state and in-kernel MMU invalidation timeline.
 *
 * Sources
 * -------
 *   trace (kvm tracepoints) -> parseTrace():               skimmed kvm_* events in [mono] clock order.
 *   eBPF (canonical NDJSON) -> parseEpt(): normalizeFrame() -> internal frame (one parser per source).
 *
 * Timeline
 * --------
 *   events are the kvm tracepoints the parser skimmed, kept in chronological order.
 *   Each event is a domain transition carried on an arrow across six lanes.
 *   Each arrow is classified travel (crosses lanes) or settle (stays in the KVM MMU lane).
 *   ept frames pair to the event that produced them via pairFrames() timestamp alignment.
 */
(function(){'use strict';
var stamp=Date.now(),TRACE_PATH='../../shared/_captures/virt-ept-Trace.txt?v='+stamp,EPT_PATH='../../shared/_captures/virt-ept.eBPF.ndjson?v='+stamp;
var events=[],frames=[],rawFrames=[],selected=0;
function $(id){return document.getElementById(id)}
function esc(s){return String(s==null?'-':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function short(x){x=String(x||'0x0');return x.length>13?x.slice(0,8)+'...'+x.slice(-4):x}
function classify(type){if(type==='kvm_entry')return{base:'travel',kind:'entry',from:3,to:5,at:4};if(type==='kvm_exit')return{base:'travel',kind:'exit',from:5,to:3,at:4};if(type==='kvm_userspace_exit')return{base:'travel',kind:'handoff',from:3,to:0,at:0};if(type==='kvm_unmap_hva_range')return{base:'travel',kind:'notify',from:1,to:3,at:2};if(type==='kvm_flush_remote_tlbs')return{base:'travel',kind:'flush',from:3,to:4,at:4};if(type==='kvm_mmu_set_spte')return{base:'settle',kind:'install',from:3,to:3,at:3};return{base:'settle',kind:'request',from:3,to:3,at:3}}
function parseTrace(text){var names='kvm_entry|kvm_exit|kvm_userspace_exit|kvm_unmap_hva_range|kvm_mmu_spte_requested|kvm_mmu_set_spte|kernel_oops_kvm_flush_\\d+';return text.split(/\r?\n/).map(function(raw){var m=raw.match(new RegExp('^\\s*(\\S+)-(\\d+)\\s+\\[(\\d+)\\]\\s+(\\S+)\\s+([0-9.]+):\\s+('+names+'):\\s+(.+)$'));if(!m)return null;var type=/^kernel_oops_kvm_flush_/.test(m[6])?'kvm_flush_remote_tlbs':m[6],e={task:m[1],pid:+m[2],cpu:+m[3],flags:m[4],time:+m[5],type:type,body:m[7],fields:{raw:m[7]}},ep=classify(type);e.base=ep.base;e.kind=ep.kind;e.from=ep.from;e.to=ep.to;e.at=ep.at;if(e.type==='kvm_entry'){var en=e.body.match(/vcpu\s+(\d+),\s+rip\s+(0x[0-9a-f]+)/i);if(en){e.fields.vcpu_id=en[1];e.fields.rip=en[2]}}else if(e.type==='kvm_userspace_exit'){var ux=e.body.match(/reason\s+(.+)$/i);if(ux)e.fields.reason=ux[1]}else if(e.type==='kvm_exit'){var ex=e.body.match(/vcpu\s+(\d+)\s+reason\s+([^\s]+)\s+rip\s+(0x[0-9a-f]+)/i);if(ex){e.fields.vcpu_id=ex[1];e.fields.exit_reason=ex[2];e.fields.rip=ex[3]}}else if(e.type==='kvm_mmu_spte_requested'){var rq=e.body.match(/gfn\s+([0-9a-f]+)\s+pfn\s+([0-9a-f]+)\s+level\s+(\d+)/i);if(rq){e.fields.gfn='0x'+rq[1];e.fields.pfn='0x'+rq[2];e.fields.level=rq[3]}}else if(e.type==='kvm_mmu_set_spte'){var sp=e.body.match(/gfn\s+([0-9a-f]+)\s+spte\s+([0-9a-f]+).*level\s+(\d+)/i);if(sp){e.fields.gfn='0x'+sp[1];e.fields.spte='0x'+sp[2];e.fields.level=sp[3]}}return e}).filter(Boolean)}
function normalizeFrame(r){var st=r.state||{};return{sequence:r.seq,time_ns:r.time_ns,timestamp_ns:r.time_ns,event_name:r.event_info&&r.event_info.event_name,event:r.event_info||{},context:r.context||{},root_hpa:st.root_hpa,root_pgd:st.root_pgd,vcpu:st.vcpu,kvm:st.kvm,mmu:st.mmu,gfns:st.gfns||[]}}
function parseEpt(text){var out=[];text.split(/\r?\n/).forEach(function(line){if(!line.trim())return;try{var r=JSON.parse(line);if(r.kind==='snapshot')out.push(normalizeFrame(r))}catch(ignore){}});return out.sort(function(a,b){return Number(a.sequence)-Number(b.sequence)})}
function pairFrames(trace,raw){var produces={kvm_entry:1,kvm_exit:1,kvm_userspace_exit:1,kvm_unmap_hva_range:1,kvm_mmu_spte_requested:1,kvm_mmu_set_spte:1,kvm_flush_remote_tlbs:1},eligible=[],assigned={},cursor=0,traceBase=0,eptBase=raw.length?Number(raw[0].timestamp_ns):0;trace.forEach(function(e,i){if(produces[e.type])eligible.push(i)});if(eligible.length)traceBase=Math.round(trace[eligible[0]].time*1e9);var absMode=eptBase?Math.abs(traceBase-eptBase)<1e9:false;raw.forEach(function(f){if(!eligible.length)return;var stamp=Number(f.timestamp_ns)-(absMode?traceBase:eptBase);while(cursor+1<eligible.length){var here=Math.abs((Math.round(trace[eligible[cursor]].time*1e9)-traceBase)-stamp),next=Math.abs((Math.round(trace[eligible[cursor+1]].time*1e9)-traceBase)-stamp);if(next>here)break;cursor++}assigned[eligible[cursor]]=f});var last=raw[0]||{};return trace.map(function(e,i){if(assigned[i])last=assigned[i];return last})}
function flowLabel(e){if(e.type==='kvm_entry')return'VM entry';if(e.type==='kvm_exit')return e.fields.exit_reason||'VM exit';if(e.type==='kvm_userspace_exit')return(e.fields.reason||'userspace exit').replace(/^KVM_EXIT_/,'').replace(/ \(.*\)$/,'');if(e.type==='kvm_unmap_hva_range')return'unmap HVA';if(e.type==='kvm_mmu_set_spte')return'SPTE changed';if(e.type==='kvm_flush_remote_tlbs')return'invalidate translations';return'SPTE requested'}
function detailTitle(e){return e.type+': '+flowLabel(e)}
function leafEntry(g){return(g&&g.entries||[]).filter(function(e){return e.leaf})[0]||{}}
function leafRange(g){var level=Number(g&&g.leaf_level||1),span=Math.pow(512,Math.max(0,level-1)),base=Math.floor(Number(g&&g.gfn||0)/span)*span;return{level:level,span:span,base:base,end:base+span-1}}
function mappedCount(f){var count=0,seen={};(f&&f.gfns||[]).forEach(function(g){if(!g.ept_mapped)return;var range=leafRange(g),leaf=leafEntry(g),key=range.level+':'+leaf.spte;if(range.level>1){if(seen[key])return;seen[key]=1;count+=range.span}else count++});return count}
function mmioCount(f){return (f&&f.gfns||[]).filter(function(g){return g.ept_mmio}).length}
function gfnRecord(f,gfn){return(f&&f.gfns||[]).filter(function(x){return Number(x.gfn)===Number(gfn)})[0]}
function gfnState(f,gfn){var g=gfnRecord(f,gfn);if(!g)return'off';if(g.ept_mmio)return'mmio';if(g.ept_mapped){var leaf=leafEntry(g);return'ram:'+g.leaf_pfn+':L'+g.leaf_level+':'+perms(leaf)+':A'+Number(leaf.a||0)+'D'+Number(leaf.d||0)}return'off'}
function sampledGfns(before,after){var set={};[before,after].forEach(function(f){(f&&f.gfns||[]).forEach(function(g){set[Number(g.gfn)]=1})});return Object.keys(set).map(Number).sort(function(a,b){return a-b})}
function stateChanges(before,after){var changes=[],seen={};sampledGfns(before,after).forEach(function(i){var ga=gfnRecord(before,i),gb=gfnRecord(after,i),huge=gb&&gb.ept_mapped&&gb.leaf_level>1?gb:ga&&ga.ept_mapped&&ga.leaf_level>1?ga:null,label='GFN '+i,target=i;if(huge){var range=leafRange(huge),key='L'+range.level+':'+range.base;if(seen[key])return;seen[key]=1;target=range.base;label=(range.span*4/1024)+' MiB leaf GFN '+range.base+'–'+range.end}var a=gfnState(before,target),b=gfnState(after,target);if(a===b)return;if(a!=='off'&&b==='off')changes.push('zap '+label+' ('+a+')');else if(a==='off'&&b!=='off')changes.push('map '+label+' → '+b);else changes.push(label+': '+a+' → '+b)});return changes}
function levelName(level){return level===4?'PML4':level===3?'PDPT':level===2?'PD':'PT'}
function eventHtml(e,i){var f=frames[i]||{},changes=stateChanges(frames[i-1],f),at=e.at*16.666+8.333,reverse=e.to<e.from?' reverse':'';if(e.base==='settle')return'<div class="journey-row"><div class="journey-path '+e.kind+' settle" style="left:'+(at-2)+'%;width:4%"></div><button class="journey-event '+e.kind+'" style="left:'+at+'%" data-index="'+i+'" type="button"><strong>'+esc(flowLabel(e))+'</strong><span>'+esc(e.kind)+'</span></button>'+(changes.length?'<div class="journey-delta">'+esc(changes.join(' · '))+'</div>':'')+'</div>';var left=Math.min(e.from,e.to)*16.666+8.333,width=Math.abs(e.to-e.from)*16.666;return'<div class="journey-row"><div class="journey-path '+e.kind+reverse+'" style="left:'+left+'%;width:'+width+'%"></div><button class="journey-event '+e.kind+'" style="left:'+at+'%" data-index="'+i+'" type="button"><strong>'+esc(flowLabel(e))+'</strong><span>'+esc(e.kind)+'</span></button>'+(changes.length?'<div class="journey-delta">'+esc(changes.join(' · '))+'</div>':'')+'</div>'}
function render(){var root=$('timeline');root.innerHTML='<div class="lane-head"><span>VMM</span><span>HOST MM</span><span>NOTIFIER</span><span>KVM MMU / EPT</span><span>vCPU / VMX</span><span>GUEST</span></div>'+events.map(eventHtml).join('');root.querySelectorAll('.journey-event').forEach(function(button){button.onclick=function(){select(+button.dataset.index)}});$('flow-summary').textContent=events.length+' transitions / '+frames.filter(function(f){return f.timestamp_ns}).length+' EPT states';select(Math.min(selected,events.length-1))}
function perms(e){return (e.r?'r':'-')+(e.w?'w':'-')+(e.x?'x':'-')}
function walkCell(e){var cls='cell '+(e.mmio?'mmio':!e.present?'off':e.leaf?'leaf':'on'),ad=e.present?' A'+Number(e.a||0)+'D'+Number(e.d||0):'';return'<div class="'+cls+'"><strong>'+esc(levelName(e.level))+'['+esc(e.index)+']</strong><span>'+(e.mmio?'MMIO ':perms(e)+ad+' ')+short(e.spte)+'</span></div>'}
function gfnRow(g,extra){var state=g.ept_mmio?'mmio':g.ept_mapped?'leaf':'off';return'<div class="leaf-row'+(extra||'')+'"><div class="cell '+state+'"><strong>GFN '+esc(g.gfn)+'</strong><span>'+short(g.gpa)+'</span></div>'+g.entries.map(walkCell).join('')+'<div class="cell '+state+'"><strong>PFN</strong><span>'+(g.ept_mmio?'MMIO':g.ept_mapped?short(g.leaf_pfn):'-')+'</span></div></div>'}
function hugeRangeHtml(g){var range=leafRange(g),leaf=leafEntry(g),sampleGfn=Number(g.gfn),pageSize=Number(g.gpa)/sampleGfn,gpaStart=range.base*pageSize,gpaEnd=(range.end+1)*pageSize-1,size=range.span*pageSize,basePfn=Number(g.leaf_pfn)-(sampleGfn-range.base);return'<div class="huge-range"><div class="huge-title"><strong>L'+range.level+' HUGE EPT LEAF</strong><span>'+(size/1048576)+' MiB · one SPTE covers '+range.span+' GFNs</span></div><div class="huge-field"><strong>GFN RANGE</strong><span>'+range.base+'–'+range.end+'</span></div><div class="huge-field"><strong>GPA RANGE</strong><span>0x'+gpaStart.toString(16)+'–0x'+gpaEnd.toString(16)+'</span></div><div class="huge-field"><strong>LEAF STATE</strong><span>'+perms(leaf)+' A'+Number(leaf.a||0)+'D'+Number(leaf.d||0)+' · '+short(leaf.spte)+'</span></div><div class="huge-field"><strong>BASE PFN</strong><span>'+short('0x'+basePfn.toString(16))+'</span></div><div class="huge-walk"><div class="huge-walk-head"><strong>REPRESENTATIVE WALK</strong><span>sampled GFN '+esc(g.gfn)+' · GPA '+short(g.gpa)+'</span></div>'+gfnRow(g,'')+'</div></div>'}
function renderWalk(f){var gfns=f.gfns||[],seen={},html='';if(!gfns.length){$('walk-detail').innerHTML='';return}gfns.forEach(function(g){if(g.ept_mapped&&g.leaf_level>1){var leaf=leafEntry(g),key=g.leaf_level+':'+leaf.spte;if(seen[key])return;seen[key]=1;html+=hugeRangeHtml(g)}else html+=gfnRow(g,'')});$('walk-detail').innerHTML=html}
function select(i){if(!events.length)return;selected=Math.max(0,Math.min(events.length-1,i));document.querySelectorAll('.journey-event').forEach(function(button){button.classList.toggle('selected',+button.dataset.index===selected)});var e=events[selected],f=frames[selected]||{},changes=stateChanges(frames[selected-1],f),fields={kind:e.base+' · '+e.kind,trace_event:e.type,transition:e.from+' → '+e.to,ept_mapped_gfns:mappedCount(f),ept_mmio:mmioCount(f),ept_delta:changes.join(', ')||'none',root_hpa:f.root_hpa,vcpu:f.vcpu};Object.keys(e.fields||{}).forEach(function(k){fields[k]=e.fields[k]});$('detail-type').textContent=e.type;$('detail-title').textContent=detailTitle(e);$('fields').innerHTML=Object.keys(fields).map(function(k){return'<dt>'+esc(k)+'</dt><dd title="'+esc(fields[k])+'">'+esc(fields[k])+'</dd>'}).join('');$('ept-event').textContent=e.type;$('ept-state').innerHTML='<div class="ept-head"><b>'+mappedCount(f)+' GFN mapped</b><span>'+mmioCount(f)+' MMIO / '+(f.gfns||[]).length+' probes</span></div>';renderWalk(f)}
Promise.all([fetch(TRACE_PATH,{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('trace HTTP '+r.status);return r.text()}),fetch(EPT_PATH,{cache:'no-store'}).then(function(r){if(!r.ok)throw Error('ept HTTP '+r.status);return r.text()})]).then(function(parts){events=parseTrace(parts[0]);rawFrames=parseEpt(parts[1]);if(!events.length)throw Error('no KVM transitions parsed');if(!rawFrames.length)throw Error('no EPT states parsed');frames=pairFrames(events,rawFrames);var startGap=Math.abs(Math.round(events[0].time*1e9)-Number(rawFrames[0].timestamp_ns)),mixed=startGap>1000000000;$('status').innerHTML='<i class="trace-dot"></i><span>'+(mixed?'mixed capture streams · relative alignment':'aligned capture streams')+' · '+events.length+' transitions · '+rawFrames.length+' EPT states</span>';render()}).catch(function(err){$('status').textContent='EPT data error · '+err.message;$('detail-title').textContent='EPT data unavailable';$('fields').innerHTML='<dt>error</dt><dd>'+esc(err.message)+'</dd>'});
})();
